package utils

const PLAYER_HEALTH = 100
const HEALTH_MIN_RESTORE = 8
const HEALTH_MAX_RESTORE = 20
const PLAYER_MIN_ATTACK = 7
const PLAYER_MAX_ATTACK = 18

const SPECIAL_ATTACK_MIN_DAMAGE = 20
const SPECIAL_ATTACK_MAX_DAMAGE = 33

const MONSTER_HEALTH = 100
const MONSTER_MIN_HEALTH_RESTORE = 12
const MONSTER_MAX_HEALTH_RESTORE = 25